#!/usr/bin/env python3
#coding: utf-8

#基于训练好的词向量模型进行聚类
#聚类采用Kmeans算法
import math
import re
import json
import jieba
import numpy as np
from gensim.models import Word2Vec
from sklearn.cluster import KMeans
from collections import defaultdict

#输入模型文件路径
#加载训练好的模型
def load_word2vec_model(path):
    model = Word2Vec.load(path)
    return model

def load_sentence(path):
    sentences = set()
    with open(path, encoding="utf8") as f:
        for line in f:
            sentence = line.strip()
            sentences.add(" ".join(jieba.cut(sentence)))
    print("获取句子数量：", len(sentences))
    return sentences

#将文本向量化
def sentences_to_vectors(sentences, model):
    vectors = []
    for sentence in sentences:
        words = sentence.split()  #sentence是分好词的，空格分开
        vector = np.zeros(model.vector_size)
        #所有词的向量相加求平均，作为句子向量
        for word in words:
            try:
                vector += model.wv[word]
            except KeyError:
                #部分词在训练中未出现，用全0向量代替
                vector += np.zeros(model.vector_size)
        vectors.append(vector / len(words))
    return np.array(vectors)


def main():
    model = load_word2vec_model(r"") #加载词向量模型
    sentences = load_sentence("")  #加载所有标题
    vectors = sentences_to_vectors(sentences, model)

    n_clusters = int(math.sqrt(len(sentences)))  #指定聚类数量
    print("指定聚类数量：", n_clusters)
    kmeans = KMeans(n_clusters)  #定义一个kmeans计算类
    kmeans.fit(vectors)          #进行聚类计算

    sentence_label_dict = defaultdict(list)
    for sentence, label in zip(sentences, kmeans.labels_):  #取出句子和标签
        # kmeans.cluester_centers_ #每个聚类中心
        sentence_label_dict[label].append(sentence)         #同标签的放到一起

    # print(kmeans.cluster_centers_) #每个聚类中心
    # print(kmeans.labels_) #每个聚类对应的ID


    cluster_dict_distance = {}
    for key, value in sentence_label_dict.items():
        # print(key, value)
        vector_tem = sentences_to_vectors(value, model)
        center_vector = kmeans.cluster_centers_[key]
        distances = np.linalg.norm(vector_tem - center_vector, axis=1)

        avg_distance = np.mean(distances)
        cluster_dict_distance[key] = avg_distance



    sorted_cluster_dict_distance = sorted(cluster_dict_distance.items(), key=lambda d: d[1], reverse=True)
    for key, value in sorted_cluster_dict_distance:
        print("cluster %s :" % key)
        for i in range(min(10, len(sentence_label_dict[key]))):  #随便打印几个，太多了看不过来
                print(sentence_label_dict[key][i].replace(" ", ""))
        print("---------")


    # for label, sentences in sentence_label_dict.items():
    #     print("cluster %s :" % label)
    #     for i in range(min(10, len(sentences))):  #随便打印几个，太多了看不过来
    #         print(sentences[i].replace(" ", ""))
    #     print("---------")

if __name__ == "__main__":
    main()
